### ISSUE TITLE
[Onprem] `sky check` with no clouds (only local) will error

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#1528]
Raising error might be an intended behavior, but I think, based on initial user feedback, we should just log to user that no clouds are enabled instead of raising error.

LOC indicated here: https://github.com/skypilot-org/skypilot/blob/master/sky/backends/backend_utils.py#L2106

**Comment by Michaelvll** [comment]
This has been fixed in the current master. Closing.

**Comment by romilbhardwaj** [comment]
Issue still exists in master, but since our ray-based onprem is being deprecated, we do not plan on fixing this in the immediate future.
