### ISSUE TITLE
Managed jobs failing with ManagedJobStatus.FAILED_CONTROLLER / JobStatus.FAILED_DRIVER (GCP)

### ISSUE THREAD

**Issue by ajayjain** [skypilot-org/skypilot#5031]
Hi SkyPilot team,

I've been trying to run 100-200 managed jobs via SkyPilot on spot L4 GPUs on GCP. However, around 2/3s of the jobs fail after 20 minutes - a few hours. Is there a way to get more insight into the crash?

```
$ sky jobs queue
ID  TASK  NAME                       RESOURCES       SUBMITTED       TOT. DURATION  JOB DURATION  #RECOVERIES  STATUS
68  -     job-077   1x[L4:1][Spot]  8 hrs ago       26m 36s        25m 5s        0            FAILED_CONTROLLER
67  -     job-0253  1x[L4:1][Spot]  9 hrs ago       4h 21m 34s     4h 20m 1s     0            FAILED_CONTROLLER
66  -     job-0240  1x[L4:1][Spot]  9 hrs ago       42m 45s        41m 10s       0            SUCCEEDED


$ sky jobs logs 68
Job 68 is already in terminal state FAILED_CONTROLLER. For more details, run: sky jobs logs --controller 68
Failure reason: Unexpected error occurred: [AssertionError] JobStatus.FAILED_DRIVER


$ sky jobs logs --controller 68
I 03-25 07:19:29 storage.py:1000] Storage type StoreType.GCS already exists.
I 03-25 07:19:29 controller.py:56] DAG:
I 03-25 07:19:29 controller.py:56] [Task<name=job-077>(run='nvidia-smi\n\n# Vali...')
I 03-25 07:19:29 controller.py:56]   resources: GCP(g2-standard-8[Spot], {'L4': 1})]
I 03-25 07:19:29 controller.py:192] Submitted managed job 68 (task: 0, name: 'job-077'); SKYPILOT_TASK_ID: sky-managed-2025-03-25-07-19-29-775067_job-077_68-0
I 03-25 07:19:29 controller.py:196] Started monitoring.
I 03-25 07:19:29 state.py:439] Launching the spot cluster...
I 03-25 07:19:32 optimizer.py:739] Target: minimizing cost
I 03-25 07:19:32 optimizer.py:752] Estimated cost: $0.2 / hour
I 03-25 07:19:32 optimizer.py:752]
I 03-25 07:19:32 optimizer.py:887] Considered resources (1 node):
I 03-25 07:19:32 optimizer.py:955] --------------------------------------------------------------------------------------------------------
I 03-25 07:19:32 optimizer.py:955]  CLOUD   INSTANCE              vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE         COST ($)   CHOSEN
I 03-25 07:19:32 optimizer.py:955] --------------------------------------------------------------------------------------------------------
I 03-25 07:19:32 optimizer.py:955]  GCP     g2-standard-8[Spot]   8       32        L4:1           asia-northeast3-a   0.20          ✔
I 03-25 07:19:32 optimizer.py:955] --------------------------------------------------------------------------------------------------------
I 03-25 07:19:34 cloud_vm_ray_backend.py:1551] ⚙︎ Launching on GCP asia-northeast3 (asia-northeast3-a).
I 03-25 07:20:18 provisioner.py:450] └── Instance is up.
I 03-25 07:20:41 provisioner.py:624] ✓ Cluster launched: job-077-68.  View logs at: ~/sky_logs/sky-2025-03-25-07-19-29-787318/provision.log
I 03-25 07:20:41 execution.py:323] ⚙︎ Mounting files.
I 03-25 07:20:46 backend_utils.py:1476]   Syncing (to 1 node): gs://skypilot-filemounts-ajay-1fb54aa4-dpdfpd6o/job-dpdfpd6o/workdir -> ~/sky_workdir
I 03-25 07:20:59 cloud_vm_ray_backend.py:4825] ✓ Files synced.  View logs at: ~/sky_logs/sky-2025-03-25-07-19-29-787318/file_mounts.log
I 03-25 07:20:59 cloud_vm_ray_backend.py:3351] ✓ Setup completed.
I 03-25 07:21:01 cloud_vm_ray_backend.py:3457] ⚙︎ Job submitted, ID: 1
I 03-25 07:21:01 cloud_vm_ray_backend.py:3493]
I 03-25 07:21:01 cloud_vm_ray_backend.py:3493] Job ID: 1
I 03-25 07:21:01 cloud_vm_ray_backend.py:3493] 📋 Useful Commands
I 03-25 07:21:01 cloud_vm_ray_backend.py:3493] ├── To cancel the job:           sky cancel job-077-68 1
I 03-25 07:21:01 cloud_vm_ray_backend.py:3493] ├── To stream job logs:          sky logs job-077-68 1
I 03-25 07:21:01 cloud_vm_ray_backend.py:3493] └── To view job queue:           sky queue job-077-68
I 03-25 07:21:01 cloud_vm_ray_backend.py:3608]
I 03-25 07:21:01 cloud_vm_ray_backend.py:3608] Cluster name: job-077-68
I 03-25 07:21:01 cloud_vm_ray_backend.py:3608] ├── To log into the head VM:     ssh job-077-68
I 03-25 07:21:01 cloud_vm_ray_backend.py:3608] ├── To submit a job:             sky exec job-077-68 yaml_file
I 03-25 07:21:01 cloud_vm_ray_backend.py:3608] ├── To stop the cluster: sky stop job-077-68
I 03-25 07:21:01 cloud_vm_ray_backend.py:3608] └── To teardown the cluster:     sky down job-077-68

I 03-25 07:21:01 recovery_strategy.py:297] Managed job cluster launched.
I 03-25 07:21:04 utils.py:135] === Checking the job status... ===
... <omitted> ...
I 03-25 07:45:42 utils.py:144] ==================================
I 03-25 07:46:02 utils.py:135] === Checking the job status... ===
I 03-25 07:46:03 utils.py:141] Job status: JobStatus.FAILED_DRIVER
I 03-25 07:46:03 utils.py:144] ==================================
E 03-25 07:46:06 controller.py:401] Traceback (most recent call last):
E 03-25 07:46:06 controller.py:401]   File "/home/gcpuser/skypilot-runtime/lib/python3.10/site-packages/sky/jobs/controller.py", line 376, in run
E 03-25 07:46:06 controller.py:401]     succeeded = self._run_one_task(task_id, task)
E 03-25 07:46:06 controller.py:401]   File "/home/gcpuser/skypilot-runtime/lib/python3.10/site-packages/sky/jobs/controller.py", line 342, in _run_one_task
E 03-25 07:46:06 controller.py:401]     assert job_status is None, job_status
E 03-25 07:46:06 controller.py:401] AssertionError: JobStatus.FAILED_DRIVER
E 03-25 07:46:06 controller.py:401]
E 03-25 07:46:06 controller.py:404] Unexpected error occurred: [AssertionError] JobStatus.FAILED_DRIVER
I 03-25 07:46:06 state.py:623] Unexpected error occurred: [AssertionError] JobStatus.FAILED_DRIVER
I 03-25 07:46:06 state.py:644] Cancellation skipped, job is already terminal
I 03-25 07:46:06 state.py:665] Cancellation skipped, job is not CANCELLING
I 03-25 07:46:07 controller.py:529] Killing controller process 137915.
I 03-25 07:46:07 controller.py:537] Controller process 137915 killed.
I 03-25 07:46:07 controller.py:539] Cleaning up any cluster for job 68.
I 03-25 07:46:08 storage.py:645] Verifying bucket for storage skypilot-filemounts-ajay-1fb54aa4-dpdfpd6o
I 03-25 07:46:08 storage.py:1000] Storage type StoreType.GCS already exists.
I 03-25 07:46:40 storage.py:1914] Deleted GCS bucket skypilot-filemounts-ajay-1fb54aa4-dpdfpd6o.
I 03-25 07:46:40 controller.py:548] Cluster of managed job 68 has been cleaned up.
✓ Job finished (status: ManagedJobStatus.FAILED_CONTROLLER).
```

I increased the size of the controller:
```
$ cat ~/.sky/config.yaml
jobs:
  controller:
    resources:
      cloud: gcp
      region: asia-northeast3
      cpus: 8+
      memory: 96+
      disk_size: 250
```

On the submission node, skypilot[gcp] is installed in a virtual env:
```
$ pip freeze | grep skypilot
skypilot==0.8.0
```

**Comment by ajayjain** [comment]
This is my yaml, run with `sky jobs launch -n job-${idx} -y -d job.yaml --env WORKER_ID=${i}`:
```
name: job

resources:
  accelerators: L4:1
  instance_type: g2-standard-8
  use_spot: true
  cloud: gcp

  job_recovery:
    max_restarts_on_errors: 3

workdir: .

setup: |
  sudo apt-get update -y
  sudo apt-get install -y ffmpeg
  pip install -q uv
  uv pip install <some packages>

run: |
  nvidia-smi
  python -m ... --rank ${WORKER_ID} --world_size ${NUM_WORKERS}

envs:
  NUM_WORKERS: 256
  OMP_NUM_THREADS: 12
  PYTHONUNBUFFERED: 1
```

It seems like the job isn't being properly auto-restarted on these errors.

**Comment by Michaelvll** [comment]
Thanks for sharing the issue @ajayjain! I am suspecting this is an issue with version 0.8 that has been fixed in nightly, but I will let @cg505 to confirm.

**Comment by ajayjain** [comment]
Issue remains on nightly:
```
$ sky --version
skypilot, version 1.0.0.dev20250325

$ sky jobs logs 1
Job 1 is already in terminal state FAILED_CONTROLLER. For more details, run: sky jobs logs --controller 1
Failure reason: Unexpected error occurred: [AssertionError] JobStatus.FAILED_DRIVER
```

Job launches also seem to be slower than on 0.8.0

**Comment by Michaelvll** [comment]
Thanks for trying it out! We are looking into this. @cg505 has more suggestion on the `FAILED_CONTROLLER` and `FAILED_DRIVER` issue in slack.

For the launching speed, you could use `--async` flag for the `jobs launch` to submit the job asnchronously, which should be much faster for submitting all the jobs in nightly:
```
for i in `seq 1 30`; do
  sky jobs launch --async job.yaml
done
```

For the log issue, it is likely because you have many parallel `jobs launch` running that tries to get the logs in parallel. With the async submission above, the log issue would be resolved as well.

Note for ourselves, when `jobs launch` is called in parallel, we should turn off the auto logging to avoid the congestion, cc'ing @aylei

**Comment by cg505** [comment]
Regarding `FAILED_DRIVER` - it looks like the underlying job clusters are somehow failing - the driver program is the management program that runs on the worker node and starts your code. It's possible this is getting OOM-killed or facing some other issue. There may not be a lot we can do to solve that issue, except to recommend to use an instance with more memory/disk/whatever seems to cause the problem.

That said, we should fix the error message and dump the job logs to make the debugging easier.

**Comment by ajayjain** [comment]
Thanks @cg505, increasing resources worked! And appreciate the tip @Michaelvll
